Resources:
  PortfolioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CyberOS_Data_${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5