default_environment: &default_environment
  GetPortfolioLogEnabled: MUST-OVERRIDE
  ManageDataLogEnabled: MUST-OVERRIDE
  ContactMeLogEnabled: MUST-OVERRIDE
  
  TableName: CyberOS_Data_${self:provider.stage}

Dev: 
  <<: *default_environment
  GetPortfolioLogEnabled: true
  ManageDataLogEnabled: true
  ContactMeLogEnabled: true

Prod:
  <<: *default_environment
  GetPortfolioLogEnabled: false
  ManageDataLogEnabled: false
  ContactMeLogEnabled: false