Resources:
  # The "Radio Station"
  KOSNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: K-OS-Notifications-${self:provider.stage}

  # The "Listener" (Your Email)
  KOSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref KOSNotificationTopic
      Endpoint: ${env:NOTIFICATION_EMAIL}