# @architecture Single-Table Design with Individual Packaging
# Every service is a standalone node project located in /services.
# Individual packaging ensures high performance and minimal zip sizes.

# Enable native .env support in V4
useDotenv: true

org: ${env:SLS_ORG}
app: ${env:SLS_APP}
service: cyber-os-backend

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'Dev'}
  logRetentionInDays: 7
  iamRoleStatements: ${file(serverless/iamRoleStatements.yml)}
  memorySize: 128
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 1
    blockPublicAccess: true
    skipPurge: false

package:
  individually: true
  include:
    - "!./**"
    - "services/utils.js"

functions: ${file(./serverless/functions.yml):functions}

resources: ${file(./serverless/dynamoDB.yml)}
