service: cyber-os-backend

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment: ${file(serverless/environment.yml)}
  iamRoleStatements: ${file(serverless/iamRoleStatements.yml)}

functions: ${file(./functions.yml):functions}

resources: ${file(./dynamoDB.yml)}